---
- name: Make {{ podman_dir }}/{{ container_name }} directory
  ansible.builtin.file:
    path: "{{ podman_dir }}/{{ container_name }}"
    state: directory
    mode: "0770"

- name: Make sure the {{ container_name }} container is created and running
  containers.podman.podman_container:
    name: '{{ container_name }}'
    image: "docker.io/mumblevoip/mumble-server:latest"
    state: 'started'
    ports:
      - 64738:64738
      - 64738:64738/udp
    volumes:
      - "{{ podman_dir }}/{{ container_name }}:/data"
    env:
      'TZ': '{{ timezone }}'
    restart_policy: unless-stopped
