---
- name: Make sure the {{ container_name }} container is created and running
  containers.podman.podman_container:
    name: '{{ container_name }}'
    image: "docker.io/mumblevoip/mumble-server:latest"
    state: 'started'
    volumes:
      - "{{ podman_dir }}/{{ container_name }}:/data"
    env:
      'TZ': '{{ timezone }}'
    ports:
      - 64738:64738
      - 64738:64738/udp
    restart_policy: unless-stopped
