---
- name: Make sure the {{ container_name }} container is created and running
  containers.podman.podman_container:
    name: "{{ container_name }}"
    image: "ghcr.io/linuxserver/sonarr"
    networks:
      - name: swag
        ipv4_address: "{{ ip_address }}"
    state: 'started'
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
    volumes:
      - "{{ podman_dir }}/{{ container_name }}:/config"
      - /media/sda-crypt/jellyfin/tv:/tv
      - /media/sdb-crypt/toronto:/downloads
    restart_policy: unless-stopped
    ports:
      - 8989:8989
