---
- name: Make {{ podman_dir }}/{{ container_name }} directory
  ansible.builtin.file:
    path: "{{ podman_dir }}/{{ container_name }}"
    state: directory
    mode: "0770"

- name: Add {{ username }} to video group
  become: true
  user:
    name: "{{ username }}"
    groups:
      - video
    append: true

- name: Make sure the {{ container_name }} container is created and running
  containers.podman.podman_container:
    name: "{{ container_name }}"
    image: "lscr.io/linuxserver/tvheadend:latest"
    networks:
      - name: swag
        ipv4_address: "{{ ip_address }}"
    state: 'started'
    env:
      "TZ": "{{ timezone }}"
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
    volumes:
      - "{{ podman_dir }}/{{ container_name }}/config:/config"
      - "{{ podman_dir }}/{{ container_name }}/recordings:/recordings"
    devices:
      - /dev/dvb:/dev/dvb
    groups:
      - keep-groups
    restart_policy: unless-stopped
    generate_systemd:
      {
        path: "/home/{{ username }}/.config/systemd/user"
      }
