---
- name: Make sure the diun container is created and running
  docker_container:
    name: '{{ container_name }}'
    image: "crazymax/diun:latest"
    pull: true
    state: 'started'
    env:
      PUID: "{{ guid }}"
      PGID: "{{ guid }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart_policy: unless-stopped
