---

- name: Make {{ docker_dir }}/{{ container_name }} directory
  become: false
  ansible.builtin.file:
    path: "{{ docker_dir }}/{{ container_name }}"
    state: directory
    mode: "0770"

- name: Make sure the {{ container_name }} container is created and running
  community.docker.docker_container:
    name: '{{ container_name }}'
    image: "docker.io/crazymax/diun:latest"
    state: 'started'
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    env:
      'TZ': '{{ timezone }}'
      "LOG_LEVEL": "info"
      "LOG_JSON": "false"
      "DIUN_WATCH_WORKERS": "20"
      "DIUN_WATCH_SCHEDULE": "0 */6 * * *"
      "DIUN_PROVIDERS_DOCKER": "true"
      "DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT": "true"
      "DIUN_NOTIF_DISCORD_MENTIONS": "@here,@everyone"
      "DIUN_NOTIF_DISCORD_WEBHOOKURL": "{{ diun_webhook }}"
    restart_policy: always
