---
- hosts: all
  become: true

  roles:
      #
      # Basics
      #
      - role: system
        tags:
            - system
      # - role: tvheadend
      #  tags:
      #      - services

      - role: podman
        tags:
            - podman
      #
      # System containers
      #
      - role: containers/system/diun
        become: false
        tags:
            - diun
            - containers
        when: enable_diun | default(False)
