---
- hosts: all
  become: false

  roles:
      #
      # Basics
      #
      - role: system
        become: true
        tags:
            - system
      # - role: tvheadend
      #  tags:
      #      - services

      - role: podman
        become: true
        tags:
            - podman

      - role: nfs
        become: true
        tags:
            - nfs
        when: enable_nfs | default(False)
      #
      # System containers
      #
      - role: containers/system/diun
        tags:
            - diun
            - containers
        when: enable_diun | default(False)

      - role: containers/system/swag
        tags:
            - swag
            - containers
        when: enable_swag | default(False)

      - role: containers/services/heimdall
        tags:
            - heimdall
            - services
            - containers
        when: enable_heimdall | default(False)
      - role: containers/services/mumble
        tags:
            - mumble
            - services
            - containers
        when: enable_mumble | default(False)
      - role: containers/services/nextcloud
        tags:
            - nextcloud
            - services
            - containers
        when: enable_nextcloud | default(False)
      - role: containers/services/uptime-kuma
        tags:
            - uptime-kuma
            - services
            - containers
        when: enable_uptime_kuma | default(False)

      - role: containers/services/jmusicbot
        tags:
            - jmusicbot
            - services
            - containers
        when: enable_jmusicbot | default(False)

      - role: containers/media/tvheadend
        tags:
            - tvheadend
            - media
            - containers
        when: enable_tvheadend | default(False)
      - role: containers/media/jellyfin
        tags:
            - jellyfin
            - media
            - containers
        when: enable_jellyfin | default(False)
      - role: containers/media/prowlarr
        tags:
            - prowlarr
            - media
            - containers
        when: enable_prowlarr | default(False)
      - role: containers/media/radarr
        tags:
            - radarr
            - media
            - containers
        when: enable_radarr | default(False)
      - role: containers/media/sonarr
        tags:
            - sonarr
            - media
            - containers
        when: enable_sonarr | default(False)
      - role: containers/media/bazarr
        tags:
            - bazarr
            - media
            - containers
        when: enable_bazarr | default(False)
      - role: containers/media/jellyseerr
        tags:
            - jellyseerr
            - media
            - containers
        when: enable_jellyseerr | default(False)
      #
      # Minecraft containers
      #
      - role: containers/minecraft/velocity
        tags:
            - velocity
            - minecraft
            - containers
        when: enable_minecraft_velocity | default(False)
