---
- name: Make sure the {{ container_name }} container is created and running
  containers.podman.podman_container:
    name: "{{ container_name }}"
    image: "docker.io/fallenbagel/jellyseerr:latest"
    networks:
      - name: swag
        ipv4_address: "{{ ip_address }}"
    state: 'started'
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
    volumes:
      - "{{ podman_dir }}/{{ container_name }}:/app/config"
    restart_policy: unless-stopped
