---
- name: Make {{ docker_dir }}/{{ container_name }} directory
  become: false
  ansible.builtin.file:
    path: "{{ docker_dir }}/{{ container_name }}"
    state: directory
    mode: "0770"

- name: Make sure the {{ container_name }} container is created and running
  community.docker.docker_container:
    name: '{{ container_name }}'
    image: 'docker.io/collabora/code'
    networks:
      - name: nextcloud_network
        ipv4_address: "{{ ip_address }}"
    state: 'started'
    env:
      'aliasgroup1': "https://nextcloud.natgo.xyz:443,https://nextcloud\\.natgo\\.xyz"
      'username': '{{ collabora_username }}'
      'password': '{{ collabora_password }}'
      'extra_params': '--o:ssl.enable=true'
      'PUID': '{{ guid }}'
      'PGID': '{{ guid }}'
      'TZ': '{{ timezone }}'
    restart_policy: unless-stopped
