---
- name: Make {{ docker_dir }}/{{ container_name }} directory
  become: false
  ansible.builtin.file:
    path: "{{ docker_dir }}/{{ container_name }}"
    state: directory
    mode: "0770"

- name: Make sure the {{ container_name }} container is created and running
  community.docker.docker_container:
    name: '{{ container_name }}'
    image: "docker.io/louislam/uptime-kuma:1"
    networks:
      - name: swag
        ipv4_address: "{{ ip_address }}"
    state: 'started'
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/app/data"
    env:
      'TZ': '{{ timezone }}'
    restart_policy: unless-stopped
