---
- name: Ubuntu specific tasks
  become: true
  when: ansible_facts['distribution'] == 'Ubuntu'
  block:
  - name: Remove cloud related stuff to avoid boot delay
    apt:
      name:
        - cloud-config
        - cloud-init
        - cloud-initramfs-dyn-netconf
        - cloud-initramfs-copymods
        - cloud-guest-utils
      state: absent

  - name: Make sure iSCSId and Open-iSCSId services are disabled
    service:
      name: "{{ item }}"
      state: stopped
      enabled: false
    with_items:
      - iscsid
      - open-iscsi

  - name: Remove open-iscsi
    apt:
      name:
        - open-iscsi
      state: absent
  - name: Remove byobu
    apt:
      name:
        - byobu
      state: absent

- name: Update and upgrade apt packages (Debian and Ubuntu)
  when: ansible_os_family == 'Debian'
  apt:
    upgrade: true
    autoremove: true
    update_cache: true

- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  reboot:
    msg: Rebooting due to a kernel update
  when: reboot_required_file.stat.exists

- name: Install extra packages
  package:
    name: "{{ extra_packages }}"
    state: present

- name: Disable cron e-mail notifications
  cron:
    name: MAILTO
    user: root
    env: true
    job: ""
