---
- name: Disable ssh password auth
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  notify: reload sshd

- name: Disable ssh root login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PermitRootLogin prohibit-password"
    line: "PermitRootLogin no"
  notify: reload sshd
