---
- name: "Check if snap is installed"
  package_facts:
    manager: "auto"

- name: Remove snap functionality
  when: "'snapd' in ansible_facts.packages"
  block:
  - name: Unmount the core* snaps
    mount:
      name: "/snap/core*"
      state: unmounted

  - name: Remove the snap package from apt
    apt:
      package: snapd
      state: absent
      purge: yes

  - name: Remove the snap folders
    file:
      name: "{{ item }}"
      state: absent
    with_items:
      - /home/{{ username }}/snap
      - /snap
      - /var/snap
      - /var/lib/snapd
      - /var/cache/snapd
      - /run/snapd-snap.socket
      - /run/snapd.socket
      - /etc/apt/apt.conf.d/20snapd.conf