---
- name: Add TVheadend repository from PPA
  block:
    - name: Check if the key exists
      stat:
        path: /etc/apt/trusted.gpg.d/tvheadend.gpg
      register: signing_key

    - name: Add the signing key
      ansible.builtin.shell: curl "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xa0d47ab4e99ff9f9c0ea949a26f4ef8440618b66" | gpg --dearmor -o /etc/apt/trusted.gpg.d/tvheadend.gpg
      when: not signing_key.stat.exists

    - name: Add TVheadend source
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/tvheadend.gpg] https://ppa.launchpadcontent.net/mamarley/tvheadend-git/ubuntu {{ ansible_distribution_release }} main"
        state: present
