---

- name: Install Podman
  when: ansible_facts['os_family'] == 'Debian'
  ansible.builtin.apt:
    name: "{{ podman_packages }}"
    state: present

- name: Make /srv user writeable
  ansible.builtin.file:
    path: /srv
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Make {{ podman_dir }} directory
  become: false
  ansible.builtin.file:
    path: "{{ podman_dir }}"
    state: directory
    mode: "0770"

- name: Create the swag network
  become: false
  containers.podman.podman_network:
    name: swag
    subnet: "{{ swag_network }}"
    gateway: "{{ swag_gateway }}"

# - name: Handle persistent data
#   become: no
#   when: "enable_nas_stuff | default(False)"
#   block:
#   - name: Check if the persistent data folder exists on the remote machine
#     stat:
#       path: "{{ podman_dir }}"
#     register: persistent_data
#     when: "enable_nas_stuff | default(False)"
#
#   - name: Check if the persistent data folder is empty
#     find:
#       paths:
#         - "{{ podman_dir }}/"
#       recurse: yes
#     register: persistent_data_find
#     when: "enable_nas_stuff | default(False)"
#
#   - name: Create the persistent data folder on the remote machine
#     file:
#       dest: "{{ podman_dir }}"
#       state: directory
#       owner: "{{ username }}"
#       group: "users"
#       mode: "ug=rwx,o=rx,g+s"
#       recurse: yes
#     when: not persistent_data.stat.exists
#
# - name: Chmod the data folder
#   become: yes
#   file:
#     dest: "{{ podman_dir }}"
#     state: directory
#     owner: "{{ username }}"
#     mode: "0775"
#     group: "users"
#     recurse: yes
