---

- name: Add podman repo
  block:
    - name: Check if the key exists
      ansible.builtin.stat:
        path: /etc/apt/trusted.gpg.d/podman.gpg
      register: podman_signing_key

    - name: Download the signing key
      ansible.builtin.get_url:
        url: https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_22.04/Release.key
        dest: /etc/apt/trusted.gpg.d/podman
        mode: 0644
      when: not podman_signing_key.stat.exists

    - name: Dearmor the key
      ansible.builtin.command: gpg --dearmor /etc/apt/trusted.gpg.d/podman
      when: not podman_signing_key.stat.exists

    - name: Remove temp key
      ansible.builtin.file:
        dest: /etc/apt/trusted.gpg.d/podman
        state: absent
      when: not podman_signing_key.stat.exists

    - name: Add the repo to sources
      ansible.builtin.template:
        src: "podman_repo.j2"
        dest: /etc/apt/sources.list.d/podman.list
        mode: 0644

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

- name: Install Podman
  when: ansible_facts['os_family'] == 'Debian'
  ansible.builtin.apt:
    name: "{{ podman_packages }}"
    state: present

- name: Enable Podman socket
  become: false
  ansible.builtin.systemd:
    name: podman.socket
    enabled: true
    state: started
    scope: user

- name: Make /srv user writeable
  ansible.builtin.file:
    path: /srv
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Make {{ podman_dir }} directory
  become: false
  ansible.builtin.file:
    path: "{{ podman_dir }}"
    state: directory
    mode: "0770"

- name: Make systemd directory
  become: false
  ansible.builtin.file:
    path: "/home/{{ username }}/.config/systemd/user"
    state: directory
    mode: "0770"

- name: Check if user is lingering
  ansible.builtin.stat:
    path: "/var/lib/systemd/linger/{{ username }}"
  register: user_lingering

- name: Enable lingering
  ansible.builtin.command: "loginctl enable-linger {{ username }}"
  when: not user_lingering.stat.exists

- name: Create the swag network
  become: false
  containers.podman.podman_network:
    name: swag
    subnet: "{{ swag_network }}"
    gateway: "{{ swag_gateway }}"

- name: Create the minecraft network
  become: false
  containers.podman.podman_network:
    name: minecraft
    subnet: "{{ minecraft_network }}"
    gateway: "{{ minecraft_gateway }}"

# - name: Handle persistent data
#   become: no
#   when: "enable_nas_stuff | default(False)"
#   block:
#   - name: Check if the persistent data folder exists on the remote machine
#     stat:
#       path: "{{ podman_dir }}"
#     register: persistent_data
#     when: "enable_nas_stuff | default(False)"
#
#   - name: Check if the persistent data folder is empty
#     find:
#       paths:
#         - "{{ podman_dir }}/"
#       recurse: yes
#     register: persistent_data_find
#     when: "enable_nas_stuff | default(False)"
#
#   - name: Create the persistent data folder on the remote machine
#     file:
#       dest: "{{ podman_dir }}"
#       state: directory
#       owner: "{{ username }}"
#       group: "users"
#       mode: "ug=rwx,o=rx,g+s"
#       recurse: yes
#     when: not persistent_data.stat.exists
#
# - name: Chmod the data folder
#   become: yes
#   file:
#     dest: "{{ podman_dir }}"
#     state: directory
#     owner: "{{ username }}"
#     mode: "0775"
#     group: "users"
#     recurse: yes
