---

- name: Make {{ docker_dir }}/{{ container_name }} directory
  become: false
  ansible.builtin.file:
    path: "{{ docker_dir }}/{{ container_name }}"
    state: directory
    mode: "0770"

- name: "Add config file for {{ container_name }}"
  become: false
  ansible.builtin.template:
    src: "jmusicbot_config.j2"
    dest: "{{ docker_dir }}/{{ container_name }}/config.txt"
    mode: "0660"
  notify: Restart jmusicbot

- name: Make sure the {{ container_name }} container is created and running
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: "docker.io/bas0korver/jmusicbot:latest"
    state: 'started'
    env:
      "TZ": "{{ timezone }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/opt/jmusicbot/config"
    restart_policy: unless-stopped
