---
- name: Install NFS kernel server
  apt:
    package: "{{ nfsd_package }}"
    state: present

- name: "nfsd: Configure exports"
  template:
    src: "exports.j2"
    dest: "/etc/exports"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: reload nfsd

- name: "nfsd: Enable and start nfsd services"
  ansible.builtin.service:
    name: "{{ nfsd_package }}"
    enabled: true
    state: started
