---

- name: Make sure the {{ container_name }} container is created and running
  containers.podman.podman_container:
    name: '{{ container_name }}'
    image: "lscr.io/linuxserver/swag"
    state: 'started'
    ports:
      - 80:80
      - 443:443
    volumes:
      - "{{ podman_dir }}/{{ container_name }}:/config"
    env:
      'TZ': '{{ timezone }}'
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "URL": "{{ domain }}"
      "SUBDOMAINS": "jellyfin,nextcloud,bluemap,status,request"
      "VALIDATION": "http"
      "DHLEVEL": "2048"
      "ONLY_SUBDOMAINS": "false"
      "STAGING": "false"
    networks:
      - name: swag
        ipv4_address: "{{ ip_address }}"
    restart_policy: unless-stopped
    generate_systemd:
      {
        path: "/home/{{ username }}/.config/systemd/user"
      }
