---
- name: Make sure the {{ container_name }} container is created and running
  containers.podman.podman_container:
    name: "{{ container_name }}"
    image: "lscr.io/linuxserver/heimdall"
    networks:
      - name: swag
        ipv4_address: "{{ ip_address }}"
    state: 'started'
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
    volumes:
      - "{{ podman_dir }}/{{ container_name }}:/config"
    restart_policy: unless-stopped
    ports:
      - 4555:80
      - 4556:443
