---
- name: Make {{ docker_dir }}/minecraft/{{ container_name }} directory
  become: false
  ansible.builtin.file:
    path: "{{ docker_dir }}/minecraft/{{ container_name }}"
    state: directory
    mode: "0770"

- name: Make sure the {{ container_name }} container is created and running
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: "docker.io/itzg/minecraft-server"
    networks:
      - name: minecraft
        ipv4_address: "{{ ip_address }}"
    state: 'started'
    ports:
      - 6969:6969
    env:
      "TYPE": "PAPER"
      "VERSION": "1.19.2"
      "MEMORY": "8G"
      "EULA": "TRUE"
      "TZ": "{{ timezone }}"
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
    volumes:
      - "{{ docker_dir }}/minecraft/{{ container_name }}:/data"
    restart_policy: unless-stopped
