---
- name: Make {{ docker_dir }}/{{ container_name }} directory
  become: false
  ansible.builtin.file:
    path: "{{ docker_dir }}/{{ container_name }}"
    state: directory
    mode: "0770"

- name: Make sure the {{ container_name }} container is created and running
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: "lscr.io/linuxserver/bazarr"
    networks:
      - name: swag
        ipv4_address: "{{ ip_address }}"
    state: 'started'
    ports:
      - 6767:6767
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/config"
      - /media/sda-crypt/jellyfin/tv:/tv
      - /media/sda-crypt/jellyfin/movies:/movies
      - /media/sdb-crypt/jellyfin/movies:/ssdmovies
    restart_policy: unless-stopped
